### ISSUE TITLE
Power button does not work

### ISSUE THREAD

**Issue by hanses89** [thoukydides/homebridge-homeconnect#112]
I can’t seem to power on or off my oven.

**Comment by thoukydides** [comment]
This is almost certainly the same as #83 and #99, i.e. a Home Connect API bug. If so, it should be reported here: https://developer.home-connect.com/support/contact

However, since you haven't bothered to provide any of the requested information (plugn version, homebridge verrsion, appliance part number, log file, etc) I can't investigate further.
