### ISSUE TITLE
Power State in Version 0.16.2

### ISSUE THREAD

**Issue by Kohle81** [thoukydides/homebridge-homeconnect#12]
Hi,

if I update from 0.16.1 to 0.16.2 the Power Switch doesn‘t show the correct state.

If I‘m going back to 0.16.1, all is correct.

Thanks for all the work you are doing with this plugin 👍

**Comment by DJay-X** [comment]
Strange. I also installed 0.16.2 right away and tried a bit. I turned the coffee machine on/off at least 20 times for testing. Currently runs perfectly and reacts quickly and without any errors. Both via App (Eve) and HomePod Siri.

**Comment by thoukydides** [comment]
Thank you @Kohle81 for reporting this.

The actual bug was introduced in version 0.6.0 (as part of change 862d92a38167d0dccfcbc1ae899dd9294bf61fb4) but it was only revealed by a change made in this latest release. I did not spot this prior to release because I do most of the testing using the [appliance simulators](https://developer.home-connect.com/simulator/) but they do not have power buttons...

The original bug set the power switch to off whenever the `connected` status of the appliance changed, whereas it should only be set to off when the appliance disconnects. This was hidden until this latest release because the connected status event was immediately followed by reading the power status from the appliance, which set the switch correctly.

In the latest release the plugin delays treating the appliance as connected until after it has successfully read its state, which means that the connection event occurs after the power status. This resulted in the correct state being overwritten and the power switch incorrectly set to off.

Subsequent changes to the power state should be reflected correctly to HomeKit. If this is not happening for you then please provide a Homebridge log file with debug (`-D`) enabled since there may be an additional problem that I cannot reproduce...

**Comment by Kohle81** [comment]
@thoukydides  and @DJay-X 

Thanks for your rapid answers. I have reinstalled the plugin in the version 0.16.2 an now it works 🤔🤔🤔

I don‘t know what it was for a reason....

Thanks 👍

**Comment by thoukydides** [comment]
Should be fixed in v0.16.3.
