### ISSUE TITLE
Notification only mode

### ISSUE THREAD

**Issue by booshtukka** [thoukydides/homebridge-homeconnect#124]
Firstly, this is amazing. Thank you so much for building this!

I have a washer and a dryer. Realistically I'm never going to drive any of these from HomeKit, so I'd like to be able to disable the buttons. Having the buttons visible just makes me think I'm going to accidentally trigger them with Siri. :)

What I want is just these notifications:

Program complete
Lint drawer full
Running low on detergent/conditioner
Any error state

Is there any way to only subscribe to these notifications and disable the other buttons?

Also I'm not sure how to view the current status of the program, i.e. how long is left to go and the current mode e.g. rinsing.

Thank you so much!

**Comment by thoukydides** [comment]
All of these requests/questions have been addressed previously...

You can control which Switch services are provided to start/stop programs using the `addprograms`option in the `config.json` file. See https://github.com/thoukydides/homebridge-homeconnect/wiki/config.json.

There is no configuration for disabling the creation of other Services. In particular, the `Switch` characteristics for the appliance power and active program are always created. I will not be adding configuration options to disable those, since their functionality is so integral to the architecture of this plugin.

The Home Connect API only reports different stages of a program for the Roxxter cleaning robot. For all other appliances each program is treated as being a single function, with only the elapsed/remaining time and percentage completion changing. Please refer to https://api-docs.home-connect.com/events?#availability-matrix for the information that is available.

The remaining program duration is provided as the `Remaining Program` characteristic on the active program `Switch` service. This is not displayed by Apple's Home app, but is shown in some third-party HomeKit apps. See https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Mapping and https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Apps.

**Comment by booshtukka** [comment]
The washer and dryer aren't triggering notifications except for the doors being opened and closed. The Home Connect app sends me various other notifications. I'd at least like a notification when the programme is completed - is this not possible?

**Comment by thoukydides** [comment]
That is the correct behaviour. The Apple Home app will only generate actual notifications for a very limited set of characteristics - mainly those that it associates with security, e.g. Doors. Only Apple can add HomeKit notifications for other characteristic types.

However, as you have pointed out, the Home Connect app provides its own notifications for things like programs finishing. What would be the point of HomeKit duplicating the same notifications, even if it could?

This plugin does provide `Stateless Programmable Switch` characteristics for events like programs finished. These can be used to trigger automations. See https://github.com/thoukydides/homebridge-homeconnect/wiki/Functionality and https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Mapping#stateless-programmable-switch-services-for-events.

For Dryer appliances the `Stateless Programmable Switch` buttons are:
1. `BSH.Common.Event.ProgramFinished`: Program Finished
2. `BSH.Common.Event.ProgramAborted`: Program Aborted

For Washer and WasherDryer appliances they are:
1. `BSH.Common.Event.ProgramFinished`: Program Finished
2. `BSH.Common.Event.ProgramAborted`: Program Aborted
3. `LaundryCare.Washer.Event.IDos1FillLevelPoor`: i-Dos 1 Low
4. `LaundryCare.Washer.Event.IDos2FillLevelPoor`: i-Dos 2 Low

Additionally, the `Switch` characteristic for the active program also indicates when the program is running. This is visible in the Home app and can also be used to trigger automations.
