### ISSUE TITLE
Authorisation issue

### ISSUE THREAD

**Issue by orangecoding** [thoukydides/homebridge-homeconnect#125]
I'm running the latest version of your plugin and follow your docu step by step.

After I created said application in the dev portal and copied the client it, I get this output every 60 seconds.

```
[13/02/2023, 20:33:30] [HomeConnect] Home Connect API error: Unable to authorise Home Connect application; request rejected by client authorization authority (developer portal). Visit https://developer.home-connect.com/applications to register an application and then copy its Client ID.
```

The id is correct, I checked it a few times.

The plugin also shows a url in the config: 
```
https://api.home-connect.com/security/oauth/device_verify?user_code=xxx
```

If I click it, and click on verify, it says
```
The code entered is invalid or has expired. Please compare your input with the information shown on the device display.
```
so I'm totally stuck

**Comment by thoukydides** [comment]
It often takes around 15 minutes for a change on the Home Connect Developer Portal to be fully deployed to the production authorisation servers. When you created the application it probably displayed a message warning you about that at the top of the browser window, but you might not have noticed that since it disappears after a few seconds.

The code in the verification URL only remains valid for 10 minutes. If you get a `The code entered is invalid or has expired` error then that suggests that you are not using a sufficiently recent link... but it might also be due to information on the authorisation servers only having been partially updated.

Authorisation definitely works in this plugin if correctly configured and enough time is allowed after creating/editing the application. I went through the process successfully many times yesterday.

Try again later without changing anything on the Home Connect Developer Portal. Restart Homebridge and click on the verification link while it is still fresh. If it still doesn't work then I suggest you contact the Home Connect team at https://developer.home-connect.com/support/contact

**Comment by orangecoding** [comment]
The verification link doesn't change (as in it is not logged), the only place I see this link is in the configuration part of the plugin.

**Comment by thoukydides** [comment]
If the verification link appears in the plugin's configuration within the homebridge-config-ui-x web interface then it will definitely have been written to the log file.

Assuming that you are using a released version of this plugin rather than checking out the latest version from github then a new URL will be generated every 10 minutes. This is written to the log file each time it is generated. However, to see the new link in the configuration editor you will need to close the configuration and re-open it.

**Comment by orangecoding** [comment]
Ok. Works now. Thanks mate
