### ISSUE TITLE
Unable to Control Coffee Machine in HomeKit

### ISSUE THREAD

**Issue by BlackJoker90** [thoukydides/homebridge-homeconnect#149]
### Description of Issue

I am experiencing an issue with controlling my coffee machine in HomeKit. While I can successfully control my oven, I am unable to control the coffee machine. Whenever I attempt to activate it using the switch, it displays a "Device Not Recognized" error. I have already tried restarting and reconfiguring the coffee machine, but unfortunately, these attempts were unsuccessful.

### Expected Behaviour

The coffee machine should activate and start brewing.

### Steps to Reproduce

    Open the HomeKit app on my device.
    Locate the coffee machine accessory.
    Tap on the switch to activate the coffee machine.

### Plugin Version

0.29.3 

### Environment

- OS: 16.5
- Node: 18.16.0
- Homebridge: 4.50.4 

### Home Connect Appliance(s)

SIEMENS-TI9558X1DE

### HomeKit App(s)

Apple Home

### Diagnostic Checks

- [X] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [X] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [X] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [X] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [X] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
[28/05/2023, 09:48:48] [HomeConnect] [Kaffeevollautomat] [GET available programs] Home Connect Status Code Error: [409 Conflict] Program currently not available [SDK.Error.ProgramNotAvailable]
[28/05/2023, 09:48:48] [HomeConnect] [Kaffeevollautomat] GET /api/homeappliances/SIEMENS-TI9558X1DE-68A40E3EB9D6/programs/available
```

### Configuration

```json
"clientid": "xxx",
            "simulator": false,
            "language": {
                "api": "de-DE"
            },
            "SIEMENS-HS858GXB6-68A40E3B0E40": {
                "addprograms": "none",
                "programs": []
            },
            "SIEMENS-TI9558X1DE-68A40E3EB9D6": {
                "addprograms": "custom",
                "programs": [
                    {
                        "name": "Ristretto",
                        "key": "ConsumerProducts.CoffeeMaker.Program.Beverage.Ristretto",
                        "selectonly": false
```

**Comment by thoukydides** [comment]
Unfortunately, nothing in this bug report tells me what might going wrong. I do not have access to a Home Connect coffee maker, so cannot try this myself. I cannot reproduce the issue with the simulated appliances.

What do you mean by "the switch". With the configuration you provided I would expect either 3 or 4 `Switch` services to be created for your appliance:
* Power
* Active Program
* "Custom" Program (Ristretto)
* (If supported) Cup Warmer

By default the Apple Home app will probably show these as a single tile with a single Switch, and toggling that combined switch will try to set the state of all 3 or 4 switches. Coffee maker appliances take a long time to start-up and shut-down, so if it controls the Power switch at the same time as trying to start a program then that would be expected to fail.

I have never seen a "Device Not Recognized" error in the Home app. Are you sure it wasn't "Not responding", which is the error displayed for any underlying problems, and doesn't help to diagnose the cause?

The excerpt from the log that you provide does not appear to be related to the problem reported. That is for an attempt to read the list of programs supported by the appliance, and there are many reasons why that can expectedly fail. Those log lines have nothing to do with attempting to start a program.

Please:
* Run Homebridge with debug logging enabled. Either run it with the `-D` command line switch, or with the `"debug": ["Log API Bodies", "Log Debug as Info"]` added to your config.json file.
* Provide a full log, not just two lines.
* Provide a clearer description of what you were trying to do (ideally with the time, so that it can be correlated with the log), and a description of what if anything the appliance did.

**Comment by BlackJoker90** [comment]
Thank you for your detailed response and suggestions. I would like to update you that the issue has been resolved. Interestingly, I didn't make any changes to the configuration; thus, I suspect that the issue was due to some transient server errors on Home Connect's side.

Now, everything seems to be working as desired. Considering this, I believe we can close this ticket.

I appreciate your assistance and time.
