### ISSUE TITLE
Error loading plugin "homebridge-homeconnect"

### ISSUE THREAD

**Issue by FlorinFrance** [thoukydides/homebridge-homeconnect#195]
### Description of Issue

25/12/2023 20:53:24HOOBSERROR Error loading plugin "homebridge-homeconnect"
25/12/2023 20:53:24HOOBSERROR ReadableStream is not defined

the plugin does not working anymore, please help

### Expected Behaviour

working plugin

### Steps to Reproduce

when bridge started

### Plugin Version

0.36.0

### Environment

- OS: HOOBS
- Node: 16.20.2
- Homebridge: 1.6.0

### Home Connect Appliance(s)

EX675LEV1F/35

### Diagnostic Checks

- [ ] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [X] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [X] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [X] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [X] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
25/12/2023 20:53:24HOOBSERROR Error loading plugin "homebridge-homeconnect"
25/12/2023 20:53:24HOOBSERROR ReadableStream is not defined
```

### Configuration

```json
{
    "platform": "HomeConnect",
    "clientid": "XXXXXXXXXXXXXXXX"
}
```

**Comment by thoukydides** [comment]
Sorry, this is not a HOOBS plugin.
I do not support its use under HOOBS.

If you can reproduce the problem with vanilla Homebridge then please re-open this issue and I will investigate. Otherwise, please contact HOOBS support.

(At least one issue is that you are running Node 16, whereas this plugin requires a minimum of Node 18 in compliance with the Homebridge verified plugin requirements. This requirement is specified in the `package.json` file and checked when the plugin starts.)
