### ISSUE TITLE
Unable to read options of unavailable programs

### ISSUE THREAD

**Issue by JerGitHub** [thoukydides/homebridge-homeconnect#201]
### Plugin Version

0.37.2

### Home Connect Appliance(s)

Thermador PRD486WDHU/01

### Log File

```shell
YELLOW WARNING BELOW
--------------------
[12/31/2023, 3:39:30 PM] [homebridge-homeconnect] [Oven Right] 4 of 7 programs advertised by appliance currently unavailable:
[12/31/2023, 3:39:30 PM] [homebridge-homeconnect] [Oven Right]     True Convection   (Cooking.Oven.Program.HeatingMode.HotAir)
[12/31/2023, 3:39:30 PM] [homebridge-homeconnect] [Oven Right]     Roast             (Cooking.Oven.Program.HeatingMode.IntensiveHeat)
[12/31/2023, 3:39:30 PM] [homebridge-homeconnect] [Oven Right]     Convection Broil  (Cooking.Oven.Program.HeatingMode.HotAirGrilling)
[12/31/2023, 3:39:30 PM] [homebridge-homeconnect] [Oven Right]     Sabbath           (Cooking.Oven.Program.HeatingMode.SabbathProgramme)
[12/31/2023, 3:39:30 PM] [homebridge-homeconnect] [Oven Right] Switching appliance on to read program options

RED WARNING BELOW
-----------------
[12/31/2023, 3:39:31 PM] [homebridge-homeconnect] [Oven Right] [SET BSH.Common.Setting.PowerState=BSH.Common.EnumType.PowerState.On] Home Connect Status Code Error: [409 Conflict] BSH.Common.Setting.PowerState currently not available or writable [SDK.Error.InvalidSettingState]
[12/31/2023, 3:39:31 PM] [homebridge-homeconnect] [Oven Right] PUT /api/homeappliances/THERMADOR-PRD486WDHU-68A40E268B0A-340/settings/BSH.Common.Setting.PowerState

YELLOW WARNING BELOW
--------------------
[12/31/2023, 3:39:31 PM] [homebridge-homeconnect] [Oven Right] 1 of 7 programs missing options (program never available to read supported options):
[12/31/2023, 3:39:31 PM] [homebridge-homeconnect] [Oven Right]     Sabbath   (Cooking.Oven.Program.HeatingMode.SabbathProgramme)
[12/31/2023, 3:39:31 PM] [homebridge-homeconnect] [Oven Right] 4 of 7 programs could not be selected (details of supported options may be unreliable):
[12/31/2023, 3:39:31 PM] [homebridge-homeconnect] [Oven Right]     True Convection   (Cooking.Oven.Program.HeatingMode.HotAir)
[12/31/2023, 3:39:31 PM] [homebridge-homeconnect] [Oven Right]     Convection Broil  (Cooking.Oven.Program.HeatingMode.HotAirGrilling)
[12/31/2023, 3:39:31 PM] [homebridge-homeconnect] [Oven Right]     Warm              (Cooking.Oven.Program.HeatingMode.KeepWarm)
[12/31/2023, 3:39:31 PM] [homebridge-homeconnect] [Oven Right]     Proof             (Cooking.Oven.Program.HeatingMode.Proof)
```

### Additional Information

Alexander - Thanks as always for the great plug-in. I was one of the first to grab it when you released it a few years ago. It's been rock solid for me the entire time. I noticed you were going crazy with updates at the end of the year and while I am not encountering any bugs, figured I would share a few of the error warnings I get in yellow and red from the logs to see if it would help with your code.

Let me know if you need me to try anything or require additional info. 

Happy New Year!

**Comment by thoukydides** [comment]
That all looks perfectly normal due to idiosyncrasies of the Home Connect API.

At start-up the plugin reads all the appliance capabilities. It caches previous results for a few reasons:
* To reduce the risk of hitting the very strict API rate limits
* To provide a fallback when the appliance is not in a suitable state to provide its capabilities
* To avoid needing to switch the appliance on and cycle through its programs or modes to read their details on every start-up

The log entries you copied are all related to the initialisation of programs...

> ```
> [Oven Right] 4 of 7 programs advertised by appliance currently unavailable:
> [Oven Right]     True Convection   (Cooking.Oven.Program.HeatingMode.HotAir)
> [Oven Right]     Roast             (Cooking.Oven.Program.HeatingMode.IntensiveHeat)
> [Oven Right]     Convection Broil  (Cooking.Oven.Program.HeatingMode.HotAirGrilling)
> [Oven Right]     Sabbath           (Cooking.Oven.Program.HeatingMode.SabbathProgramme)
> ```

That's pretty self-explanatory. The API is reporting that the Oven supports 7 programs, but says that only 3 of them are currently available for use. The other 4 cannot be selected for some reason.

My oven always reports the Sabbath program as supported but unavailable. That's because it needs to be explicitly enabled in the settings before it can be selected, and I leave it disabled. The Sabbath program was only added to the API recently, so that issue didn't show previously.

I have no idea why the True Convection, Roast, or Convection Broil programs might be unavailable. But that's an issue with the appliance (or the Home Connect API). There's nothing that this plugin can do about it, other than to provide a warning.

> ```
> Switching appliance on to read program options
> ```

If the plugin has never been able to properly read and cache the options for one or more programs then it will attempt to do so. Most appliances only reliably report the options for a program when it is currently selected on the appliance. Hence, the plugin attempts to switch the appliance on, so that it can select the program and read its options.

> ```
> [Oven Right] [SET BSH.Common.Setting.PowerState=BSH.Common.EnumType.PowerState.On] Home Connect Status Code Error: [409 Conflict] BSH.Common.Setting.PowerState currently not available or writable [SDK.Error.InvalidSettingState]
> [Oven Right] PUT /api/homeappliances/THERMADOR-PRD486WDHU-68A40E268B0A-340/settings/BSH.Common.Setting.PowerState
> ```

In this case the Home Connect API rejected the request to turn on the appliance power. The error suggests a temporary problem. This can be for many reasons, such as the appliance being busy, communication issues, or transient errors within the Home Connect servers.

> ```
> [Oven Right] 1 of 7 programs missing options (program never available to read supported options):
> [Oven Right]     Sabbath   (Cooking.Oven.Program.HeatingMode.SabbathProgramme)
> ```

Like my Oven, yours never allows the Sabbath program to be selected. Hence, its options have never been read.

> ```
> [Oven Right] 4 of 7 programs could not be selected (details of supported options may be unreliable):
> [Oven Right]     True Convection   (Cooking.Oven.Program.HeatingMode.HotAir)
> [Oven Right]     Convection Broil  (Cooking.Oven.Program.HeatingMode.HotAirGrilling)
> [Oven Right]     Warm              (Cooking.Oven.Program.HeatingMode.KeepWarm)
> [Oven Right]     Proof             (Cooking.Oven.Program.HeatingMode.Proof)
> ```

At some point these programs have been available, but for some reason it has not been possible to select them. The plugin also attempts to update options when a program is manually selected, so it appears that you have never used these programs whilst the plugin is running.

Hence, it was only possible to read the options for these programs when they were not selected. That's better than nothing, but as the log message indicates the appliance may offer different options (or different valid ranges for the options) when the programs are selected.

This mostly affects the options presented in the Homebridge UI configuration editor. It doesn't have any impact on the plugin operation unless you want to configure Switch services to start these programs with options that the plugin has not seen.

Those log entries should have been followed by something like this to explain:

```
[Oven Right] This could be entirely expected if some programs are never available for use (e.g. some appliances require Sabbath programs to be enabled in the appliance setting before they can be selected)
[Oven Right] Unavailable programs may also be due to bugs in the appliance firmware or Home Connect API service
[Oven Right] However, if these programs should be usable then these steps may help resolve the issue:
[Oven Right]     1.  Ensure that the appliance is in a suitable state to allow selection of all programs:
[Oven Right]       (a)  Replenish any consumables that are low or empty
[Oven Right]       (b)  Complete any required cleaning or other maintenance operations
[Oven Right]       (c)  Ensure that the appliance has power and that no program is active
[Oven Right]       (d)  Leave the appliance idle for a few minutes (so that it can be controlled remotely)
[Oven Right]     2.  Manually select (but do not start) each program on the appliance, leaving the appliance idle for a couple of minutes after each selection:
[Oven Right]       (a)  Sabbath mode
[Oven Right]     3.  Trigger this plugin to re-read the details of all programs using one of these methods:
[Oven Right]       (a)  Restart the Homebridge instance for this plugin
[Oven Right]       (b)  Invoke the HomeKit "Identify" routine for this appliance (e.g. using the "ID" button in the Eve app)
```

Anyway, I don't see anything in those log entries that suggests a problem with the plugin.

**Comment by JerGitHub** [comment]
nope - no problems at all. I was just sending in case the logs helped you add anything to your code.

thanks again for everything - this plugin is great - happy new year!
