### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by JerGitHub** [thoukydides/homebridge-homeconnect#21]
#### Description of Issue
Received Syntax Error from HomeConnect which shutdown Homebridge. Since I wasn't in debug, I am not sure if this will give you enough info to go on but thought I would share in case. I will try to reproduce the issue but was using Siri to control the hood vent fan and worked fine and then received the syntax error at some point and couldn't turn it off. Checked logs and saw homebridge was stopped.

I wonder if using the oven and the dishwasher caused the errors when looking at the log?

#### Plugin Version
0.16.9

#### Log File
[HC syntax error.txt](https://github.com/thoukydides/homebridge-homeconnect/files/4252861/HC.syntax.error.txt)

**Comment by thoukydides** [comment]
The Home Connect event stream sometimes contains spurious characters. It looks to me like the result of debugging code that someone forgot to remove; I reported it to the Home Connect team about a month ago but have not received a response.

I have been making changes to the plugin to try and detect these spurious characters and trigger a restart of the event stream to recover. The particular case that you show in the log should be fixed by dd10c277db6b0642f89a1fae74b12bcf94c0ba4a in v0.17.0 and later.

**Comment by JerGitHub** [comment]
ah ok - thanks! I was trying to reproduce it with no luck so sounds like what you are saying is the reason.

**Comment by thoukydides** [comment]
In my experience the event stream starts getting garbage characters about once a week. Previous workarounds trapped the most common cases. This particular failure I have only ever seen once.
