### ISSUE TITLE
HomeConnect API unexpected values (WQB245B0BY/01)

### ISSUE THREAD

**Issue by TBD** [thoukydides/homebridge-homeconnect#230]
### Plugin Version

0.38.0

### Home Connect Appliance(s)

Bosch Dryer WQB245B0BY/01

### Log File

```shell
// Union types
export type ProgramKey =
    'LaundryCare.Dryer.Program.BusinessShirts'
  | 'LaundryCare.Dryer.Program.Cotton'
  | 'LaundryCare.Dryer.Program.Cotton.CottonEco' // (unrecognised)
  | 'LaundryCare.Dryer.Program.Delicates'
  | 'LaundryCare.Dryer.Program.DownFeathers'
  | 'LaundryCare.Dryer.Program.Hygiene'
  | 'LaundryCare.Dryer.Program.Mix'
  | 'LaundryCare.Dryer.Program.Super40'
  | 'LaundryCare.Dryer.Program.Synthetic'
  | 'LaundryCare.Dryer.Program.TimeCold'
  | 'LaundryCare.Dryer.Program.TimeWarm'
  | 'LaundryCare.Dryer.Program.Towels';
```

### Additional Information

is it possible to show the time remaining ? it shows 12 switch buttons named Dryer that doesn't help 😋

thank you

**Comment by thoukydides** [comment]
Thanks for the report. The `LaundryCare.Dryer.Program.Cotton.CottonEco` program will be added in the next release.

It would have been preferable to create separate issues/discussions for the other items you raise...

> is it possible to show the time remaining ?

It is already exposed to HomeKit, and can be seen in third-party HomeKit apps, such as [The Eve App](https://www.evehome.com/en/eve-app). This is covered in the documentation, and previous issues/discussions:
* https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Mapping#extra-active-program-switch-characteristics
* https://github.com/thoukydides/homebridge-homeconnect/wiki/Functionality
* https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Apps
* #48, #68, #114, #218, #225, etc...

> it shows 12 switch buttons named Dryer that doesn't help 😋

Do you mean `Switch` services for starting programs, or `Stateless Programmable Switch` buttons that can trigger automations from Home Connect events?

I am guessing the former, since Dryer appliances should only support 5 events, not 12. The switches should have unique names. This was improved as a result of #196, although it may require the Apple Home app to be force-quit and restarted to take effect. If that doesn't help, then a workaround is to open the settings for each switch in the Home app, delete the appliance name, and it will reveal the correct name. You can then manually rename them appropriately (although this really shouldn't be required).

**Comment by thoukydides** [comment]
`LaundryCare.Dryer.Program.Cotton.CottonEco` is in [v0.39.0](https://github.com/thoukydides/homebridge-homeconnect/releases/tag/v0.39.0).
