### ISSUE TITLE
Option to disable the active program button? 

### ISSUE THREAD

**Issue by malmentm** [thoukydides/homebridge-homeconnect#240]
### Description of Enhancement

Would it be possible to add an option to disable the active program button? I just need a simple power button for the device :)

### Home Connect Appliance(s)

Siemens TP703R09/02

**Comment by thoukydides** [comment]
Whilst that's certainly doable, I decided against making the [active program `Switch` service](https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Mapping#switch-service-for-active-program) optional because it supports quite a lot of features distributes through the plugin:
* `On`, `Status Active`, and `Status Fault` characteristics: Indicates current appliance operation state.
* `On` characteristic: Starts/stops/pauses/resumes the active program. (Completely separate implementation to that indicating the operation state).
* `Remaining Duration` characteristic: Indicates time remaining until program finishes.

All of the other services that can currently be disabled in the configuration are simple features with self-contained implementations. However, in this case multiple independent features in the plugin assume that this service exists (for appliance types that support those features), so making it optional will introduce additional coupling between those features which I am not sure I want. A user disabling the service will also lose features that they might not be expecting to be affected.

I will think about it...

**Comment by thoukydides** [comment]
That's in [v0.40.0](https://github.com/thoukydides/homebridge-homeconnect/releases/tag/v0.40.0).

**Comment by malmentm** [comment]
WOW Awesome! :)
