### ISSUE TITLE
Initiate a power-on while pressing the a beverage button.

### ISSUE THREAD

**Issue by malmentm** [thoukydides/homebridge-homeconnect#242]
### Description of Enhancement

Hello!
Would it be possible to initiate a power-on automatically when you press a beverage button? So if the machine is in OFF state when a beverage button is pressed it would start the machine and wait for it to be ready and then  serve the beverage?

**Comment by thoukydides** [comment]
Probably not.

The appliances that I have access to switch themselves on when a program is started. It is not necessary to switch the appliance on first, or wait for the appliance to be ready. Hence, I would not be able to test functionality like this.

This plugin does not currently implement any sequencing of operations when triggered from HomeKit. The only time it does anything along these lines is during first-use when it needs to read details of the appliance's supported programs, and that is very much a best-effort affair that often fails. I would be very reluctant to attempt anything similar for normal usage.

CoffeeMaker appliances already cause a lot of problems for this plugin, with different models behaving differently, especially regarding their on/off sequencing. Some models do not indicate their power state reliably, whilst others do not report this operation state consistently. It is tricky to get the existing plugin behaviour to work adequately with all these variations without trying anything more convoluted.

Anyway, would this feature even be useful? Most CoffeeMaker appliances perform a cleaning cycle when switched on, so it would be necessary to wait for that to complete and then place the cup under the spout before the drink is produced.

This sort of appliance and user-specific sequencing is more appropriately implemented using the Shortcuts app.

**Comment by malmentm** [comment]
Thanks for the answer, my coffee machine has an option to skip rinse when powered on remotely. But I guess I could accomplish this with a shortcut instead. Anyways thanks for the answers.

**Comment by thoukydides** [comment]
Probably the most important reason why I don't want to implement this is that it would break my own usage of the plugin...

Currently when HomeKit sets the state of a characteristic this plugin waits for the result from the Home Connect API before responding to HomeKit to indicate whether it was successful. However, the delay before responding to HomeKit needs to be kept short because it stalls other HomeKit activity. This is just about acceptable when it just waiting for a simple Home Connect API response, but that would not be OK if it was necessary to wait for the appliance to become ready to sequence further operations. For that the plugin would need to return a success result to HomeKit immediately, and continue the sequence in the background... at which point HomeKit never gets informed if the operation fails for any reason.

I mostly use this plugin to control my appliances via Siri when I am not in the same room (or even at home), so the verbal feedback of whether the operation worked is important... otherwise I could return to find that my meal is not ready when expected.
