### ISSUE TITLE
Feature Request: Configurable Option to allow user to decide if devices should go offline (Not Responding) in HomeKit

### ISSUE THREAD

**Issue by badgertastic** [thoukydides/homebridge-homeconnect#251]
### Description of Enhancement

I would say, certainly in the case of Washers and Driers, people don't leave these on, not even in standby. Yet also people don't want devices disconnected in Home app as it shows as abnormal status on Home app menu.

Proposing to add configurable option to adjust this behaviour. Thanks.

**Comment by thoukydides** [comment]
Sorry, but no. I really do not want to add configuration options for detailed behaviour like this. I think the plugin configuration is already too complicated, with too many options likely to confuse new users. There needs to be an extremely strong justification for new configuration options, especially ones like this that I would not use myself.

More importantly, a significant proportion of this plugin is already untested before I make releases - either due to not having access to Home Connect appliances with the associated functionality, or the time required to try every feature and option. Each extra configuration option (that I do not use myself) just adds more untested code.

In this case I believe that the current behaviour is entirely appropriate. It is consistent with how my native HomeKit devices behave - the Home app reports them as Not Responding when they are unplugged. For my Home Connect appliances it is also definitely the appropriate way to handle them being disconnected. It is also the best match for the Home Connect API - if the appliance is disconnected (which can be due to a Wi-Fi/internet/cloud connectivity issue) then it does not provide any information other than the static appliance details such as model and serial number. The API, and hence this plugin, have no information about whether the appliance is switched off at the mains or has a communication issue. Hence, the only state that can be correctly reported to HomeKit is that there is `SERVICE_COMMUNICATION_FAILURE`.

**Comment by badgertastic** [comment]
Ok fair enough. But FYI I'm not disconnecting the Dryer or Washing Machine from the mains. I'm simply pressing the On/Off button at the end of the cycle. Otherwise the display is left on and goes to standby pause blinking light. It's the usual and recommended behaviour for energy conscious households.

**Comment by thoukydides** [comment]
That button is disconnecting the appliance from the mains - it is just doing that internally instead of at the wall socket. The effect is the same. As far as the Home Connect API servers are concerned the appliance has just disappeared.

All of my Home Connect appliances have soft power switches. They turn off the appliance display, but leave the appliance connected to the Home Connect servers. The only time that they disconnect from the Home Connect servers is when they are disconnected externally or the internet connection goes down. I originally assumed that all Home Connect appliances behaved that way since the API documentation doesn't suggest otherwise. It is also the only behaviour that fits in with how HomeKit expects accessories to function.

**Comment by badgertastic** [comment]
Then the dryer and washing machine i have clearly aren’t suitable for your plugin. Have removed. My life will be simpler.

**Comment by flschweiger** [comment]
I'd love to contribute to this discussion as well. First, a big thanks to @thoukydides for this fantastic plugin! I have a washer/dryer unit that I also completely power off when not in use (like many others, I imagine). I use the active program virtual switch to get notifications when the laundry is ready, but I’m not interested in using the machine’s on/off switch.

It’s frustrating that washers and dryers disconnect entirely when turned off, and I understand @badgertastic's point about the non-responding accessory. This isn’t ideal because you constantly receive 'some accessories are not responding' messages, which appear as warnings in the Home app. That’s why this plugin isn’t currently practical for me either, unless:

1. We can disable the device’s power state, using only the switches/buttons for active programs, the door sensor, or starting a specific program.
2. The last power state is cached for dryers/washers (similar to virtual switches).

I’d love to hear your thoughts on this. Thanks again for all your hard work!

**Comment by thoukydides** [comment]
Please see the [`Disconnected as Off`](https://github.com/thoukydides/homebridge-homeconnect/wiki/Experimental-Features#disconnected-as-off) experimental feature added in [v1.9.0](https://github.com/thoukydides/homebridge-homeconnect/releases/tag/v1.9.0).
