### ISSUE TITLE
Exactly one specific Program is not starting anymore - ConsumerProducts.CoffeeMaker.Program.Beverage.Espresso

### ISSUE THREAD

**Issue by DJay-X** [thoukydides/homebridge-homeconnect#26]
@thoukydides Hey there.
I noticed a while ago that I can't start one specific coffee program anymore.
`ConsumerProducts.CoffeeMaker.Program.Beverage.Espresso`
Neither in the Home/Eve App or by Siri. The device is always showing "not responding".
All other programs and the coffee maker itself work.

Has something changed from home connect server side? The Espresso program did work in the past.

Now I thought of maybe deleting a cached file to "reset"
But can't figure out which one to delete safely. 
Sorry to bother but hope you can help what the best solution is and why this happened.

Thanks in advance.

![Bildschirmfoto 2020-05-09 um 17 56 01](https://user-images.githubusercontent.com/3874239/81478831-08a71d80-9220-11ea-8aa6-d83d5f7c146a.png)

```
[2020-5-9 17:43:47] [HomeConnect] [Kaffeevollautomat] START Program 'Espresso' (ConsumerProducts.CoffeeMaker.Program.Beverage.Espresso)
[2020-5-9 17:43:52] [HomeConnect] [Kaffeevollautomat] Home Connect API error: HomeAppliance did not respond in time, it might by offline [SDK.Error.HomeAppliance.Connection.Initialization.Failed]
[2020-5-9 17:43:52] [HomeConnect] [Kaffeevollautomat] START active program ConsumerProducts.CoffeeMaker.Program.Beverage.Espresso
[2020-5-9 17:43:52] [HomeConnect] [Kaffeevollautomat] PUT https://api.home-connect.com/api/homeappliances/BOSCH-CTL636ES6-xxx/programs/active
[2020-5-9 17:45:24] [HomeConnect] [Kaffeevollautomat] START Program 'Americano' (ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Americano)
[2020-5-9 17:45:25] [HomeConnect] [Kaffeevollautomat] Inactive, attention required (ActionRequired)
[2020-5-9 17:45:25] [HomeConnect] [Kaffeevollautomat] Active (Run)
[2020-5-9 17:45:25] [HomeConnect] [Kaffeevollautomat] Program 'Americano' (ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Americano) active
[2020-5-9 17:45:25] [HomeConnect] [Kaffeevollautomat] Selected program null is not supported by the Home Connect API
[2020-5-9 17:46:44] [HomeConnect] [Kaffeevollautomat] Inactive (Finished)
[2020-5-9 17:46:44] [HomeConnect] [Kaffeevollautomat] Program 'Americano' (ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Americano) inactive
[2020-5-9 17:46:44] [HomeConnect] [Kaffeevollautomat] Inactive (Ready)
[2020-5-9 17:49:47] [HomeConnect] [Kaffeevollautomat] Manual mode (remote start allowed, being operated locally)
[2020-5-9 17:49:51] [HomeConnect] [Kaffeevollautomat] Remote operation enabled (remote start allowed)
[2020-5-9 17:49:53] [HomeConnect] [Kaffeevollautomat] Inactive, attention required (ActionRequired)
[2020-5-9 17:49:53] [HomeConnect] [Kaffeevollautomat] Manual mode (remote start allowed, being operated locally)
[2020-5-9 17:49:53] [HomeConnect] [Kaffeevollautomat] Active (Run)
[2020-5-9 17:49:53] [HomeConnect] [Kaffeevollautomat] Program 'Americano' (ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Americano) active
[2020-5-9 17:49:53] [HomeConnect] [Kaffeevollautomat] Selected program null is not supported by the Home Connect API
[2020-5-9 17:49:57] [HomeConnect] [Kaffeevollautomat] Remote operation enabled (remote start allowed)
[2020-5-9 17:51:07] [HomeConnect] [Kaffeevollautomat] Inactive (Finished)
[2020-5-9 17:51:07] [HomeConnect] [Kaffeevollautomat] Program 'Americano' (ConsumerProducts.CoffeeMaker.Program.CoffeeWorld.Americano) inactive
[2020-5-9 17:51:08] [HomeConnect] [Kaffeevollautomat] Inactive (Ready)
```

homebridge@1.0.4, homeconnect@0.18.0

**Comment by thoukydides** [comment]
> I noticed a while ago that I can't start one specific coffee program anymore.
> `ConsumerProducts.CoffeeMaker.Program.Beverage.Espresso`
> Neither in the Home/Eve App or by Siri. The device is always showing "not responding".
> All other programs and the coffee maker itself work.

It sounds like the appliance no longer supports that program. It could be that it has been renamed, although the [API documentation](https://developer.home-connect.com/docs/coffee-maker/supported_programs_and_options) still lists it with that name.

> Has something changed from home connect server side?

I do not have any inside knowledge about whether things have changed on the server side. It is possible that Home Connect have changed which programs are supported. However, the [changelog](https://developer.home-connect.com/changelog) does not show any recent changes) that are relevant. More likely possibilities are that your appliance has received a software update, or just a temporary glitch.

> Now I thought of maybe deleting a cached file to "reset"
> But can't figure out which one to delete safely.

This plugin only uses cached results if either (i) they were read from the appliance within the last 24 hours, or (ii) an error occurs trying to read from the appliance. If it is a case of the appliance now supporting a different list of programs then the easiest way to force a refresh is to use the HomeKit ***Identify*** method. This will show information about the supported programs in the log and rebuild the configuration schema.

However, if you want to try deleting the cache files then you can find details in this project's [Wiki](https://github.com/thoukydides/homebridge-homeconnect/wiki/Files#plugin-persistent-cache).

Do not delete any of the files that you have listed. Those are all managed by Homebridge, not by this plugin. Nothing relevant to the Home Connect API is stored in those files.

The relevant cache files are those in the `~/.homebridge/homebridge-homeconnect/persist` directory (or the equivalent for the homebridge instance being used). 

I would recommend keeping the `94a08da1fecbb6e8b46990538c7b50b2` file, otherwise you would need to reauthorise your account with the Home Connect servers. All of the other files in that directory can be safely deleted (while homebridge is stopped); they will all be regenerated automatically with no loss of information.

> ```
> [2020-5-9 17:43:47] [HomeConnect] [Kaffeevollautomat] START Program 'Espresso' (ConsumerProducts.CoffeeMaker.Program.Beverage.Espresso)
> [2020-5-9 17:43:52] [HomeConnect] [Kaffeevollautomat] Home Connect API error: HomeAppliance did not respond in time, it might by offline [SDK.Error.HomeAppliance.Connection.Initialization.Failed]
> ```

Unsurprisingly this is not one of the [documented API errors](https://developer.home-connect.com/docs/general/apierrors)... but it is one that tends to be returned when the Home Connect servers [cannot reach the appliance](https://github.com/thoukydides/homebridge-homeconnect/wiki/Errors#home-connect-appliance-unreachable).

**Comment by DJay-X** [comment]
@thoukydides  Thanks for your reply. I appreciate your participation. 🙏

> use the HomeKit Identify method
This showed that the Espresso program is available like it always was. 🤷🏼‍♂️

```
{
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                 "name": "Espresso",
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                 "key": "ConsumerProducts.CoffeeMaker.Program.Beverage.Espresso",
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                 "options": {
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                     "ConsumerProducts.CoffeeMaker.Option.CoffeeTemperature": "ConsumerProducts.CoffeeMaker.EnumType.CoffeeTemperature.94C",
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                     "_ConsumerProducts.CoffeeMaker.Option.CoffeeTemperature": [
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                         "ConsumerProducts.CoffeeMaker.EnumType.CoffeeTemperature.90C",
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                         "ConsumerProducts.CoffeeMaker.EnumType.CoffeeTemperature.94C",
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                         "ConsumerProducts.CoffeeMaker.EnumType.CoffeeTemperature.95C"
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                     ],
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                     "ConsumerProducts.CoffeeMaker.Option.BeanAmount": "ConsumerProducts.CoffeeMaker.EnumType.BeanAmount.Normal",
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                     "_ConsumerProducts.CoffeeMaker.Option.BeanAmount": [
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                         "ConsumerProducts.CoffeeMaker.EnumType.BeanAmount.VeryMild",
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                         "ConsumerProducts.CoffeeMaker.EnumType.BeanAmount.Mild",
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                         "ConsumerProducts.CoffeeMaker.EnumType.BeanAmount.Normal",
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                         "ConsumerProducts.CoffeeMaker.EnumType.BeanAmount.Strong",
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                         "ConsumerProducts.CoffeeMaker.EnumType.BeanAmount.VeryStrong",
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                         "ConsumerProducts.CoffeeMaker.EnumType.BeanAmount.DoubleShot",
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                         "ConsumerProducts.CoffeeMaker.EnumType.BeanAmount.DoubleShotPlus",
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                         "ConsumerProducts.CoffeeMaker.EnumType.BeanAmount.DoubleShotPlusPlus"
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                     ],
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                     "ConsumerProducts.CoffeeMaker.Option.FillQuantity": 40,
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                     "_ConsumerProducts.CoffeeMaker.Option.FillQuantity": "Int [35 .. 60] step 5 ml"
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:                 }
Mai 09 19:20:46 raspberrypi-3BPlus homebridge[456]:             },

```

So nothing to change in the config.json

I deleted the 130b... and 9821... file and restarted homebrigde. After this the Espresso switch was responding again and also Siri was able to start the program.

I keep in mind as a "reset" that deleting these two files can help without loss of other information or setup.  Didn't find that in the Wiki. My fault.

Thanks again for your quick help. Espresso evening is saved. ;)

**Comment by thoukydides** [comment]
Glad you got it working again.

I don’t suppose you kept a copy of the old cache files before deleting them? It would have interesting to see what changed that fixed the problem...

**Comment by DJay-X** [comment]
Hmm.. No, sorry. Straight ahead deleted it. Next time. ;)

**Comment by thoukydides** [comment]
No worries. I was expecting that to be the case.

Hopefully it won’t fail like this again...
