### ISSUE TITLE
HomeConnect API access_denied & login session expired

### ISSUE THREAD

**Issue by CSchmidtDD** [thoukydides/homebridge-homeconnect#295]
### Description of Issue

Hey, I thought this to be a duplicate of #121, but it is a brand new problem.

I've setup my SingleKey Account and this plugin once successfully, but had to recreate homebridge from scratch and entered the saved ClientID from the Developers page again. Got a link in the logs, klicked on that and after entering my "normal" Useraccount I get a plain JSON-Response with:
`{
  "error": "access_denied",
  "error_description": "login session expired"
}`

Even if I go to Plugin Settings, refresh the token and re-re-recheck all applicationo "settings", recreated homebrdige, reinstalled the plugin ono earllier versions and so on - to no avail. The very first install was without pproobllems and everything was fine - now this out of the blue.

Hope you can guide me to more information that I can give you.
There are neither warnings nor errors in the loogs, except the reocurring "click that link".

I can login to the singleKeyID and developer account no problem. Also tried different browsers, no dice.

### Expected Behaviour

Clicking the link, logging in, everything fine.

### Steps to Reproduce

Setup homebridge and the plugin as stated in Readme.

### Plugin Version

1.0.2

### Environment

- OS: ubuntu jammy (22.04.4 LTS), latest homebridge/homebridge docker container
- Node: 20.17.0
- Homebridge: 1,6,4
- homebrdige-UI: 4.54.1

### Diagnostic Checks

- [ ] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [ ] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [X] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [X] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [X] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
[9/4/2024, 9:53:40 PM] [HomeConnect] Initializing HomeConnect platform...
[9/4/2024, 9:53:40 PM] [HomeConnect] homebridge-homeconnect version 1.0.2
[9/4/2024, 9:53:40 PM] [HomeConnect] Node.js version 20.17.0 (satisfies >=22.0.0 || ^20.12.2 || ^18.20.2)
[9/4/2024, 9:53:40 PM] [HomeConnect] Homebridge version 1.8.4 (satisfies ^1.8.0|| ^2.0.0-beta.0)
[9/4/2024, 9:53:40 PM] [HomeConnect] Homebridge API version 2.7 (satisfies ^2.7)
[9/4/2024, 9:53:40 PM] [HomeConnect] Homebridge HAP version 0.12.2 (satisfies >=0.9.0)
Setup Payload:
X-HM://.....
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 728-63-506 │     
    └────────────┘     
                       
[9/4/2024, 9:53:40 PM] Homebridge v1.8.4 (HAP v0.12.2) (HomeBridge) is running on port 52942.
[9/4/2024, 9:53:40 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[9/4/2024, 9:53:40 PM] [HomeConnect] Attempting authorisation
[9/4/2024, 9:53:40 PM] [HomeConnect] Unable to use saved API authorisation (No saved authorisation data found)
[9/4/2024, 9:53:40 PM] [HomeConnect] Requesting authorisation using the Device Flow
[9/4/2024, 9:53:41 PM] [HomeConnect] Please authorise access to your appliances within 30 minutes 9 seconds using the associated Home Connect or SingleKey ID email address by visiting:
[9/4/2024, 9:53:41 PM] [HomeConnect]     https://api.home-connect.com/security/oauth/device_verify?user_code=PGR8-9HNQ
```

### Configuration

```json
{
    "platform": "HomeConnect",
    "name": "HomeConnect",
    "clientid": "3C0......AE42B5B9",
    "simulator": false,
    "language": {
        "api": "de-DE"
    },
    "_bridge": {
        "username": ".......",
        "port": 52796
    }
}
```

**Comment by thoukydides** [comment]
I have just tried v1.0.2 without any saved authentication and it completes the SingleKey ID login and Home Connect authorisation without any problems. Hence, this does not appear to be a problem with either this plugin or the Home Connect servers. Neither do there appear to have been any problems with the Home Connect servers for the last couple of days.

The particular JSON error message you quote is not one that I have seen previously, and is not one listed on the Home Connect developers' site. Based on its description, I would guess that you have tried to either use the same link twice, or took too long to complete the authorisation from when the link was generated. As the log messages indicate, each link is typically usable for about 30 minutes, but if you start the authorisation using a particular link it is usually not possible to try again with the same link... although I would normally expect that to fail with a web page saying "The code entered is invalid or has expired. Please compare your input with the information shown on the device display." rather than a JSON error response.

Other than that I really cannot offer any assistance. The fact that the plugin is providing the authorisation link means that it has done its part and that your Client ID is probably valid. Everything else is down to the Home Connect servers, and so outside of my control or visibility. If you cannot resolve it yourself then I suggest you use the Contact Form at https://developer.home-connect.com/support/contact to ask the Home Connect Developer Program team for help.

**Comment by thoukydides** [comment]
I am sorry that I cannot be more help.

Unfortunately errors related to authentication tend to be quite tricky to resolve since the mechanism deliberately avoid returning any information that might help an attacker. In this case the error is from the Home Connect servers, which I do not have any visibility of whatsoever. All that I know is based on the available documentation, and experiments introducing all of the different failure causes that I can think of - none of which caused the error that you are seeing.

Hopefully the Home Connect Developer team will be able to assist.

**Comment by revilO70** [comment]
I have the exact same issue.  
"access_denied", "login session expired"

**Comment by thoukydides** [comment]
I can see that this same error has been reported in forums for other projects such as ioBroker and Hcpy. It isn't unique to this plugin... which is what I would have expected since the error is from the Home Connect / SingleKey authentication servers rather than from this plugin.

There are a few suggestions in those forums that it might be a temporary account lockout, and that waiting 24 hours fixes it. There are also suggestions that changing the account password and re-logging in everywhere also helps.

However, I still cannot reproduce this failure, and I have tried everything that I can think of. To me this suggests that the issue is related to your particular SingleKey or Home Connect Developer accounts, rather than a more general problem.

As this is a Home Connect server/account issue and nothing to do with this plugin, I really cannot do anything more to help. Sorry.

**Comment by mne86** [comment]
I installed the Plugin yesterday, and I have the same issue.

**Comment by FRFGCCEVCV** [comment]
I've just installed the plugin. Same problem here.

**Comment by FRFGCCEVCV** [comment]
After looking at the browser requests with the developer tools (Network tab), I noticed that this problem is a Homeconnect one. I realized, that one of the requests had the header "Accept-Language" and my first language was 'es-ES'. I changed the preferred languages in the browser (just the order is enough) putting 'en' (English without flavour) on the top. The authorisation worked properly and now I can see all my devices in HomeKit.

@thoukydides, please, add in your README.md a hint, telling the users to put 'en' on the top of the preferred languages on the default browser (or the used one if using copy&paste) for the authentication to work properly. This is not your bug, it's Homeconnect's, but that hint would help all international users (you have many!).
Thx!

**Comment by thoukydides** [comment]
Thank you for @FRFGCCEVCV for investigating and finding both the cause and workaround. That explains why I wasn't able to reproduce it during my tests - I always have `en-GB` as my preferred language. Changing it to `es` results in the JSON response that have been quoted in this issue.

I have reported the problem to the Home Connect Developer Program team. Since this is clearly a serious bug in their implementation, and probably a simple one to fix, I expect that they will address it quickly.

Regarding the `NOTICE TO USERS AND PLUGIN DEVELOPERS` message that you quoted from the log in your previous message, version 1.0.0 of this plugin includes the changes required to work with the current Homebridge 2 beta releases.

**Comment by madcat-nl** [comment]
For people reading this in the future, i also had some issues with activating the plugin.
There are many places where you could change your language, but the one you need to change it the Language of Homebridge.  So the account language, developer API language or language in the Home connect can stay at your own language.

So change:
Homebridge->Settings->Display->English 
Maybe refresh the homebridge page to make sure the language is changed.
