### ISSUE TITLE
Disconnection from oven every half hour or so

### ISSUE THREAD

**Issue by fate8383** [thoukydides/homebridge-homeconnect#306]
### Description of Issue

[10/19/2024, 9:15:20 AM] [HomeConnect] [Oven] Disconnected (setting On error status)
[10/19/2024, 9:15:21 AM] [HomeConnect] [Oven] Connected
[10/19/2024, 9:15:21 AM] [HomeConnect] [Oven] Off
[10/19/2024, 9:15:21 AM] [HomeConnect] [Oven] Inactive (Inactive)
[10/19/2024, 9:19:55 AM] [HomeConnect] EVENT STREAM END
[10/19/2024, 9:19:55 AM] [HomeConnect] Starting events stream for all appliances
[10/19/2024, 9:19:58 AM] [HomeConnect] [Oven] Disconnected
[10/19/2024, 9:19:58 AM] [HomeConnect] [Oven] Disconnected (setting On error status)
[10/19/2024, 9:19:58 AM] [HomeConnect] [Oven] Inactive, attention required, in error state (disconnected)

### Expected Behaviour

It should not disconnect.

### Steps to Reproduce

Simple standby mode this keeps happening, then connects again and repeats.

### Plugin Version

Latest

### Environment

- OS: rasbian latest stable
- Node: 20 latest stable 
- Homebridge: latest stable

### Home Connect Appliance(s)

Siemens oven HB 

### Diagnostic Checks

- [X] Home Connect app is able to control the appliance with Wi-Fi disabled.
- [X] Home Connect app shows three green lines in the Network section of the appliance Settings.
- [X] Unofficial [Home Connect Server Status](https://homeconnect.thouky.co.uk) shows servers up and no recent errors.
- [X] Searched for [previously reported issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and no similar ones found.
- [X] Checked the [Home Connect API errors](https://api-docs.home-connect.com/general?#api-errors) and [authorisation errors](https://api-docs.home-connect.com/authorization?#authorization-errors) documentation.

### Log File

```shell
[10/19/2024, 9:15:20 AM] [HomeConnect] [Oven] Disconnected (setting On error status)
[10/19/2024, 9:15:21 AM] [HomeConnect] [Oven] Connected
[10/19/2024, 9:15:21 AM] [HomeConnect] [Oven] Off
[10/19/2024, 9:15:21 AM] [HomeConnect] [Oven] Inactive (Inactive)
[10/19/2024, 9:19:55 AM] [HomeConnect] EVENT STREAM END
[10/19/2024, 9:19:55 AM] [HomeConnect] Starting events stream for all appliances
[10/19/2024, 9:19:58 AM] [HomeConnect] [Oven] Disconnected
[10/19/2024, 9:19:58 AM] [HomeConnect] [Oven] Disconnected (setting On error status)
[10/19/2024, 9:19:58 AM] [HomeConnect] [Oven] Inactive, attention required, in error state (disconnected)
```

### Configuration

```json
Simple one device setting. Anything else I can provide upon request.
```

**Comment by thoukydides** [comment]
There have been a **lot** of problems with the Home Connect API over the last few days. Take a look at:
* https://homeconnect.thouky.co.uk/

Did you see this problem before 16th October? If it has only occurred since then it is probably due to the Home Connect server issues. If it occurred prior to that then it is probably due to either your Wi-Fi or internet connection. Either way there is nothing that I can do about it.

**Comment by fate8383** [comment]
Makes sense. I will monitor more and let you know. Sorry for taking your time.

**Comment by horhokokki** [comment]
That site is quite nice, but how can I get the info to the bash script or something?

**Comment by thoukydides** [comment]
@horhokokki, I assume you are referring to my *Home Connect Server Status (unofficial)* page. There used to be an official API status page but it was taken down - probably because it always indicated everything was healthy, even when it clearly wasn't.

My page monitors the ability to access my own Home Connect appliances, via the Home Connect API, from my home broadband connection. I provide the results of its monitoring on homeconnect.thouky.co.uk, in the README for this repo, and in the Homebridge UI configuration for this plugin. I do not provide it in any other form, and have no plans to do so. I am definitely not going to be providing any kind of API for third-party use.

**Comment by horhokokki** [comment]
Yeah, I figured out how to get the status from your page to my script. No need to run my automation script for coffeemaker if the api is down.

**Comment by horhokokki** [comment]
And now my checkup script is blocked and chrome too, what a bullshit.

**Comment by thoukydides** [comment]
@fate8383 it looks like the Home Connect API has been OK for the last few hours, so it might be worth checking whether you are still getting frequent disconnections. If you are, then I suggest checking whether the oven is maintaining a stable Wi-Fi connection, or having to reconnect frequently.

**Comment by fate8383** [comment]
> @fate8383 it looks like the Home Connect API has been OK for the last few hours, so it might be worth checking whether you are still getting frequent disconnections. If you are, then I suggest checking whether the oven is maintaining a stable Wi-Fi connection, or having to reconnect frequently.

You are absolutely right, it was all about the API issue, sorry again to bother you. I have been observing since you pointed out. Issue can be closed.

**Comment by thoukydides** [comment]
Thanks for confirming.

Unfortunately Home Connect API problems like this with aren't uncommon - that's why I created the monitor and status page.
