### ISSUE TITLE
China Server Support

### ISSUE THREAD

**Issue by nekopoi** [thoukydides/homebridge-homeconnect#311]
### Description of Enhancement

Installed plugin, was confused with the required fields as HomeConnect is on China Mainland server. The China Mainland server uses mobile number to login instead of SigID Email address, the Developer portal can set this up, but seems not implanted to the plugin yet. I've tried to use that as login credentials (username field) which didn't work. Home Assistant's HACS plugin, HomeConnect Alt is added the support and can be used successfully, But I'm not using HA's bridge since I'm prefer HB more:) Any possible adding this and I'm welling to provide help.

### Home Connect Mapping

Support HomeConnect China server Login

**Comment by nekopoi** [comment]
The HACS Plugin for HomeConnect Alt: https://github.com/ekutner/home-connect-hass?tab=readme-ov-file

**Comment by thoukydides** [comment]
Based on a quick look it appears that the only required change should be to use `api.home-connect.cn` instead of `api.home-connect.com` (and to mention setting the "Sync to China" option in the documentation for creating the application).

I don't recall seeing that alternative endpoint in the Home Connect API documentation previously, and there's nothing about it in the API ChangeLog, so I wonder when it was added. The earliest reference I can find to a separate endpoint for China was about a year ago.

Anyway, I will add a configuration option for this.

**Comment by nekopoi** [comment]
Great appreciated [thoukydides](https://github.com/thoukydides) !

**Comment by thoukydides** [comment]
Please try [v1.1.0](https://github.com/thoukydides/homebridge-homeconnect/releases/tag/v1.1.0).

Either add `"china": true` to `config.json` or set *Server Location* to **China** within the configuration UI.

**Comment by thoukydides** [comment]
Thanks for confirming!
