### ISSUE TITLE
Enable notifications

### ISSUE THREAD

**Issue by siclarkplugins** [thoukydides/homebridge-homeconnect#38]
Is it possible to create a sensor device based on the Program Finished, so that we can set the Home app to notify when the program finishes.  With the current setup I believe I can only trigger a scene based on the program finishing.

**Comment by thoukydides** [comment]
Technically, yes, it would be possible. However, the user interface/experience would be poor because none of the HomeKit sensor types are relevant. I also, don't see the point since the Home Connect app already generates notifications.

Can you explain what you are trying to achieve and why you think this is the right solution?

**Comment by thoukydides** [comment]
I am going to close this issue because no justification has been provided for this feature.

**Comment by siclarkplugins** [comment]
Apologies,  I missed the question.  It was just that I prefer to have all my notifications into one app rather than having to use multiple ones, plus then we can get notifications across multiple family devices including ipads and Macs.  
Its one of the main reasons to use Homekit or other HA platforms, so that we dont all have to use 8 different apps on our phones.  

However I built some logic with Eve to reflect the status back into my main HA platform, and I can use that to trigger notifications instead, its just not as neat.

**Comment by thoukydides** [comment]
It would not be neat as a notification within HomeKit.

The [HomeKit Accessory Protocol (HAP)](https://developer.apple.com/homekit/specification/) does not provide any support for accessories to generate arbitrary notifications. There are just a few pre-defined sensor types that can be used. None of them are appropriate for a Home Connect appliance finishing its program, so you would end up getting a "motion detected" or "smoke detected" notification rather than anything more relevant.
