### ISSUE TITLE
Light status and control for hoods?

### ISSUE THREAD

**Issue by cstromme** [thoukydides/homebridge-homeconnect#4]
Any chance you could add light status and control for hoods?

**Comment by thoukydides** [comment]
I have attempted to add support for these features, but am unable to test it because I do not have a Hood with Home Connect support and no simulator has been provided. The API documentation is not particularly accurate or complete so I have had to make some guesses about how appliances actually behave. I will update the README to describe the Hood support once someone has provided feedback that it actually works.

This is already being discussed under issue #2, so please add any feedback there.
