### ISSUE TITLE
Corrupt cache file

### ISSUE THREAD

**Issue by fcarucci** [thoukydides/homebridge-homeconnect#47]
#### Description of Issue
Log is constantly littered by this warning.

#### Home Connect Appliance(s)
Dishwasher 

#### Log File
(node:27377) UnhandledPromiseRejectionWarning: Error: [node-persist][readFile] /var/lib/homebridge/homebridge-homeconnect/persist/130b9cf2dc079eb8116e6fca2c2ec001 does not look like a valid storage file!
    at /usr/lib/node_modules/homebridge-homeconnect/node_modules/node-persist/src/local-storage.js:314:89
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
(node:27377) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11) (node:27377) UnhandledPromiseRejectionWarning: Error: [node-persist][readFile] /var/lib/homebridge/homebridge-homeconnect/persist/130b9cf2dc079eb8116e6fca2c2ec001 does not look like a valid storage file!
    at /usr/lib/node_modules/homebridge-homeconnect/node_modules/node-persist/src/local-storage.js:314:89
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
(node:27377) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)

**Comment by thoukydides** [comment]
Thank you for reporting this issue.

You have not specified which version of the homebridge-homeconnect plugin you are using. However, with the current version (0.19.1) I can reproduce that error by corrupting the contents of the cache file used to generate the dynamic configuration schema (see https://github.com/thoukydides/homebridge-homeconnect/wiki/Files#plugin-persistent-cache). Other problems with that file (such as it not existing or the plugin not having read/write permissions) result in different error messages.

The `/var/lib/homebridge/homebridge-homeconnect/persist/130b9cf2dc079eb8116e6fca2c2ec001` file should be properly formatted JSON data. Please can you check whether that is the case? If you don't mind, it would be helpful if you could send me a copy of that file (it contains details of the Home Connect API supported by your appliances, including their `haID` unique identifiers, but no personal information or authorisation data).

Unless there is a bug in the `node-persist` module (and the only changes to that module since the version being used are not relevant), the only ways that I can think of that would cause that file to be corrupted is if the homebridge process is killed part-way through writing the file, or if there are multiple copies of homebridge running concurrently with the same `--user-storage-path` (which would be bad for many reasons).

Has this plugin ever worked correctly for you without reporting that error in the log?
Is there a possibility that at some time you had two copies of homebridge running at the same time using the same configuration directory?

You should be able to fix your installation by:
1. Stop homebridge.
2. Delete the `/var/lib/homebridge/homebridge-homeconnect/persist/130b9cf2dc079eb8116e6fca2c2ec001` file. If you use homebridge-config-ui-x to edit the plugin's configuration then I would recommend also deleting the other cache files from the same directory, except for `94a08da1fecbb6e8b46990538c7b50b2`  (which if deleted would require the plugin to be re-authorised with the Home Connect servers).
3. Restart homebridge. 

Please let me know whether that works.

I will have a think about the best way to improve the error handling within the plugin. Probably the best approach is to treat any error reading the cache file as equivalent to the file not existing, with just a single log message on the first attempt to read it. The potential issue with that approach is that any error reading the previous authorisation data, even if transient, will require the plugin to be re-authorised with the Home Connect servers.

**Comment by thoukydides** [comment]
Version 0.19.2 should now catch errors thrown by the node-persist module.

Errors that occur whilst trying to read a cache file are treated as though the file does not exist. In most cases this will just result in the plugin re-reading the required details via the Home Connect API. However, if the file containing the OAuth tokens cannot be read then re-authorisation with the Home Connect servers will be required.

With this version it should no longer be necessary to manually delete corrupt cache files.

**Comment by fcarucci** [comment]
Hi Alexander, thanks for the quick response and fix! Sorry for not reporting the version, my bad.

Deleting the corrupt file fixed the issue, by the way. Your fix is definitely proper. I’ll update.

_________________
carucci.photography <https://carucci.photography/>

**Comment by thoukydides** [comment]
That's great. Thank you for confirming.

Did you check the contents of the `130b9cf2dc079eb8116e6fca2c2ec001` file before removing it? It would have been interesting to see whether it provided any clues as to how it got corrupted...

**Comment by fcarucci** [comment]
No, I’m sorry. I didn’t
