### ISSUE TITLE
Program not supported & terminated events stream

### ISSUE THREAD

**Issue by boehser-enkel** [thoukydides/homebridge-homeconnect#50]
#### Description of Issue
Error Log messages

#### Home Connect Appliance(s)
Siemens EQ.500 integral

#### Log File

Mostly @ night:
```
[10/03/2021, 05:14:47] [homebridge-homeconnect] Terminated events stream for all appliances: getaddrinfo EAI_AGAIN api.home-connect.com


&



[10/03/2021, 08:39:26] [homebridge-homeconnect] [Kaffeevollautomat] Selected program ConsumerProducts.CoffeeMaker.Program.CleaningModes.ApplianceOffRinsing is not supported by the Home Connect API
[10/03/2021, 08:39:26] [homebridge-homeconnect] [Kaffeevollautomat] Active (Run)
```

**Comment by thoukydides** [comment]
> ```
> [10/03/2021, 05:14:47] [homebridge-homeconnect] Terminated events stream for all appliances: getaddrinfo EAI_AGAIN api.home-connect.com
> ```

This means that your DNS server could not respond to a request. If it regularly happens around the same time then you've probably got something performing a scheduled reboot.

Do you have any reason to believe that this plugin failed to handle that error appropriately?

> ```
> [10/03/2021, 08:39:26] [homebridge-homeconnect] [Kaffeevollautomat] Selected program ConsumerProducts.CoffeeMaker.Program.CleaningModes.ApplianceOffRinsing is not supported by the Home Connect API
> [10/03/2021, 08:39:26] [homebridge-homeconnect] [Kaffeevollautomat] Active (Run)
> ```

That log message is entirely correct - the Home Connect API is behaving inconsistently.

The Home Connect event stream is reporting that the CoffeeMaker is running the `ApplianceOffRinsing` program. However, when asked for a list of supported programs that was not included in the list that the API returned. Asking the API for details of that program would have return an error; the log message indicates that the plugin avoided that (since it would have counted against the API rate limits).

I do not see any incorrect behaviour by this plugin in the information that you have provided.
@boehser-enkel please can you clarify what you consider to be a bug here?

**Comment by boehser-enkel** [comment]
So no bug. Thanks for clarification
