### ISSUE TITLE
Changing default duration on Oven programs 

### ISSUE THREAD

**Issue by Jtupz** [thoukydides/homebridge-homeconnect#55]
#### Description of Issue

Now that Oven-Control scope is authorised, Oven programs can be set from home/eve/home+. However, the default duration of these programs is 60 seconds. After 60 seconds the program finishes.   

I tried changing the default duration in the homeconnect .json file but it seems to overwrite it with the default every time. 

#### Plugin Version

v0.23.2

#### Home Connect Appliance(s)

Bosch Oven (E-Nr: HBG6764B6B/75)

#### HomeKit App(s)

Apple Home, Elgato Eve, Home+

**Comment by thoukydides** [comment]
Setting the Oven program duration works fine for me. Hence, I suspect that you have got something wrong in your `config.json` file.

Have you checked the Homebridge log file for any warnings or errors indicating that you have specified the program options incorrectly? This could be reported either when the plugin is started, or when the program is activated.

I recommend using [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x) to edit the configuration since that will only allow valid options to be selected.

If you want me to investigate then please provide:
* A copy of your `config.json` file (with any personal information like the `clientid` removed).
* The Homebridge log file (preferably captured with debug enabled using the `-D` command line switch).

This is the configuration that I am using with a Siemens iQ700 (HB678GBS6B/58) Oven:
```
{
    "bridge": {
        "name": "Homebridge Home Connect",
        "username": "…",
        "port": …,
        "pin": "…"
    },
    "platforms": [
        {
            "platform": "HomeConnect",
            "clientid": "…",
            "simulator": false,
            "language": {
                "api": "en-GB"
            },
            "SIEMENS-HB678GBS6B-…": {
                "addprograms": "custom",
                "programs": [
                    {
                        "name": "Preheat",
                        "key": "Cooking.Oven.Program.HeatingMode.HotAir",
                        "selectonly": false,
                        "options": {
                            "Cooking.Oven.Option.SetpointTemperature": 200,
                            "BSH.Common.Option.Duration": 3600,
                            "Cooking.Oven.Option.FastPreHeat": true
                        }
                    },
                    {
                        "name": "Pizza",
                        "key": "Cooking.Oven.Program.HeatingMode.PizzaSetting",
                        "selectonly": false,
                        "options": {
                            "Cooking.Oven.Option.SetpointTemperature": 275,
                            "BSH.Common.Option.Duration": 3600
                        }
                    },
                    {
                        "name": "Baked Potato",
                        "key": "Cooking.Oven.Program.HeatingMode.HotAir",
                        "selectonly": false,
                        "options": {
                            "Cooking.Oven.Option.SetpointTemperature": 180,
                            "BSH.Common.Option.Duration": 5400,
                            "Cooking.Oven.Option.FastPreHeat": false,
                            "BSH.Common.Option.StartInRelative": "09:30"
                        }
                    }
                ]
            }
        }
    ],
    "accessories": []
}
```

**Comment by Jtupz** [comment]
Apologies, I was using "No individual program switches" as opposed to a custom list. I have added custom lists for each program I want now and can set the duration. 

Thanks!

**Comment by thoukydides** [comment]
> Apologies, I was using "No individual program switches" as opposed to a custom list. I have added custom lists for each program I want now and can set the duration. 

Brilliant! Good to hear that you found the problem and managed to get it working.
