### ISSUE TITLE
Make Stateless Programmable Switches for events optional

### ISSUE THREAD

**Issue by luigi-lauro** [thoukydides/homebridge-homeconnect#56]
#### Description of Enhancement
As per title, just a small suggestion to further improve this fantastic plugin: I think not everyone needs to have all the programmable switches, with confusing numeric labels due also to Home app limitations, for automation. I think as we have options in UI to disable the manual program switches for every appliances, we should also have an option to disable the events switches for every appliances, to avoid spamming homekit with many unused/confusing switches, and just activate them for the appliances where it's needed for automation purposes. A per-appliance option would be perfect, but even a global one would work in my case. Even better a per-event option, but I think this is probably overkill and unneeded.

**Comment by thoukydides** [comment]
Sorry, but no. (At least not at the current time.)

Whilst I appreciate the reasons for this request... and other people have requested the same thing (e.g. #31)... I am not currently willing to go down the route of adding extra configurability.

In general, I am only willing to invest effort on functionality that (i) I use myself, (ii) can be added with minimal effort (e.g. where most of the implementation can be shared with features added for other reasons), or (iii) significantly improve the usability or functionality (e.g. the control of Hood fans using appropriate HomeKit services). The  `Stateless Programmable Switch` services were originally the only part of this plugin that I regularly used myself; it is only with the recent ability to start Oven programs that I use anything else.

It would require significant changes to the plugin to handle this correctly, e.g. removing the unused HomeKit services when the plugin is restarted after the configuration is changed. Unless that is done it would rely on the user deleting the `~/.homebridge/persist/IdentifierCache.XXXXXXXXXXXX.json` file, and I already get enough support requests from people who don't bother to read the documentation without the problem of leaving "zombie" HomeKit services.

Whilst I could probably hack that functionality in for the `Stateless Programmable Switch` services without too much trouble, there would then be an expectation of similar functionality to disable various other features such as the Sabbath Mode `Switch` for Oven appliances, and the various other Mode `Switch` services for Freezer/FridgeFreezer/Refrigerator/WineCooler appliances. Implementing that cleanly would require a significant rewrite. It would be even more effort to avoid breaking any existing automations that users have configured due to replacing old services with new ones when the updated plugin is first used.

The configurability for program `Switch` services was necessary to make them useful, i.e. providing a way to specify the program options. The ability to hide all of the programs came virtually for free with that feature. However, that is not the case here with the `Stateless Programmable Switch` services .

Finally, I already have an issue with test coverage since much of the functionality of this plugin cannot be exercised using either my own appliances, or the simulators on the developer website. As a result, quite a few releases have introduced serious bugs that I was unable to reproduce, but were immediately apparent to other users. Extra configurability would increase the proportion of code that won't be properly tested prior to release, which will lead to more broken releases, since realistically I will only routinely test the configuration that I use myself.

**Comment by luigi-lauro** [comment]
Thank you Alex.
All good reasons, I perfectly understand you. Maybe consider for the future at least the global switch for the switches only, I think that will also save you quite a few questions/issues/mails from people puzzled by the behavior, but that's just my idea, your choice :-)
Luigi

**Comment by thoukydides** [comment]
[v0.32.0](https://github.com/thoukydides/homebridge-homeconnect/releases/tag/v0.32.0) provides per-appliance configuration options to remove the `Stateless Programmable Switch` services for appliance events (as well as selectively enabling the `Switch` services for appliance mode settings and the `Door` services for the appliance door status).
