### ISSUE TITLE
Apple's Home app groups appliance services into two tiles by default

### ISSUE THREAD

**Issue by mano87** [thoukydides/homebridge-homeconnect#59]
Hello all,
for what reason my devices are listed twice? Oven and dishwasher?

![kitchen](https://user-images.githubusercontent.com/25568300/126880266-a21207ed-34ea-4c09-b387-5fb0738da4d4.png)

```
{
    "clientid": "lalalalalalalalala",
    "simulator": false,
    "language": {
        "api": "de-DE"
    },
    "SIEMENS-HM836GPB6-68A40E65458F9": {
        "addprograms": "none",
        "programs": []
    },
    "0110703835439008140": {
        "addprograms": "none",
        "programs": []
    },
    "platform": "HomeConnect"
}
```

**Comment by thoukydides** [comment]
That is a question for Apple, since it is the behaviour that they chose to implement as the default within their Home app.

This plugin creates a single HomeKit **Accessory** per appliance in the Home Connect account. Each **Accessory** provides a number of **Services**, such as a `Switch` service to control the power, a `Switch` to start/stop each program, and a `Stateless Programmable Switch` to report events such as alarms. For details of the different **Services** refer to the documentation:
- https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Mapping
- https://github.com/thoukydides/homebridge-homeconnect/wiki/Functionality 

It is up to individual HomeKit apps how they decide to present the user interface for each **Accessory** and its associated **Services**. Various developers have taken different approaches. For example, Elgato's [Eve](https://www.elgato.com/en/eve/eve-app) app defaults to showing each `Switch` separately but grouping the `Stateless Programmable Switch` services together, although any of these can be hidden, and clicking on any of these displays all of the accessory's **Services**.

Early versions of the Apple Home app took a similar approach, with separate tiles for most of the accessory's **Services**, but with the `Stateless Programmable Switch` services grouped on a single tile. The version in iOS 14 defaults to grouping all of the services except for the `Stateless Programmable Switch` services on one tile, and puts the `Stateless Programmable Switch` services on a second tile. However, that is just the default behaviour - you can select the `Show as separate tiles option` to restore the previous behaviour, and then the `Group with Other Accessories...` option to combine them differently.

However, for some reason, the Apple Home app does not provide the option to group the `Stateless Programmable Switch` services with the other services. That may be a deliberate design decision, although I suspect that it is simply a case that none of the accessories they tested against had both `Stateless Programmable Switch` services and other service types.

Anyway, if you want to know the reason or get the behaviour changed then you will need to contact Apple. It is a user interface design issue for their Home app.

**Comment by mano87** [comment]
@thoukydides 

Thank you for the comprehensive response.

Would not it make more sense for you to contact Apple or find a solution to this problem?

Or is it meant that I mediate between you and Apple? However, I do not know the depths of your programming ... I think the topic is in better hands with you.

**Comment by thoukydides** [comment]
I don't see this as a problem, or as anything requiring resolution. It is a design choice how a particular HomeKit app chooses to present the various accessories, services, and characteristics. Apple have changed their approach in different versions of their Home app, and will probably continue to do so. Other app developers have taken different approaches.

If you don't like how Apple's Home app does things then you can either put up with it, try to persuade them to do things differently, or use a different app.

Personally, I don't like Apple's Home app. It doesn't expose all HomeKit functionality, and has a poor user interface. This is why I generally (other than for configuring HomePods and performing firmware updates) use one of third-party alternatives: https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Apps

**Comment by mano87** [comment]
@thoukydides 

Thank you very much for the feedback. However, I am a bit surprised about your comments.

As soon as the devices are duplicated, a voice control with Siri is not possible in a meaningful way, because apparently the assignment does not work meaningfully due to the duplicated devices.

For me, it seems that I am the only one who wants to use the interface fully.

**Comment by thoukydides** [comment]
The appliances are not duplicated. As I explained previously, it is just how the Home app chooses to group the services for display. It has no effect whatsoever on Siri. I use Siri to control my Home Connect appliances without any problems whatsoever.

If you are having a problem with control via Siri then that is something completely unrelated to the Home app showing two tiles for each appliance.
