### ISSUE TITLE
Unable to authorise Home Connect application; Unauthorized client: `grant_type` is invalid

### ISSUE THREAD

**Issue by mistertropi** [thoukydides/homebridge-homeconnect#60]
Hello everyone!

Unfortunately, I can't get any further ....

The following error is in the log: Home Connect API error: Unable to authorize Home Connect application; Unauthorized client: `grant_type` is invalid

I made everything new. I'm trying to connect a dishwasher.

Thanks for the help

**Comment by thoukydides** [comment]
This will be due to either not creating a suitable application on the Home Connect website, or not configuring this plugin appropriately with the details of that application.

When you registered an application on https://developer.home-connect.com/applications/add did you remember to change the "OAuth Flow" from its default of "Authorization Code Grant Flow" to "Device Flow"?

Are you editing the config.json file for this plugin by hand, or using the homebridge-config-ui-x web-based configuration interface?

Did you ensure that the `simulator` option was set to `false` (or not specified)?

Did you copy the correct Client ID value from the Home Connect website into the plugin configuration? It must be the Client ID for the application that you created rather than the one for the automatically created API Web Client.

**Comment by mistertropi** [comment]
Thank you very much, now I am a long way ahead, thank you!

now he wants a code
https://api.home-connect.com/security/oauth/device_verify?user_code

when I enter this, the app connects to the account, but the same message appears in the log every time ...

**Comment by mistertropi** [comment]
if I want to allow access, click on it, comes:

HTTP method not allowed, supported methods: POST
I hope You can Help me

**Comment by thoukydides** [comment]
Presumably you saw something like this in the log file:
```
[HomeConnect] No saved authorisation data found
[HomeConnect] Requesting Home Connect authorisation using the Device Flow
[HomeConnect] Home Connect request #1: POST https://api.home-connect.com/security/oauth/device_authorization
[HomeConnect] Home Connect request #1: OK +425ms
[HomeConnect] Home Connect authorisation required. Please visit:
[HomeConnect]     https://api.home-connect.com/security/oauth/device_verify?user_code=1234-5678
[HomeConnect] Waiting for completion of Home Connect authorisation (poll every 5 seconds, device code 12345678-1234-1234-1234-123456789ABC expires after 600 seconds)...
```

You need to copy the whole of the https://api.home-connect.com/security/oauth/device_verify?user_code=1234-5678 link to your web browser, including the alphanumeric code (but using the one from your log file, rather than this example).

This should prompt you to login to your Home Connect account. You must use the same username and password that you used with the official Home Connect iPhone app:

![image1](https://user-images.githubusercontent.com/4775242/132184285-1b724bdc-bc5b-4ecd-8b4e-ff8b74038124.jpg)

After successfully logging in to your account you will be asked to approve access to your appliances:

![image2](https://user-images.githubusercontent.com/4775242/132184298-61d93a6d-61e1-4d2d-a613-f722d99a625e.jpg)

and will then be redirected to whatever `Redirect URI` you had specified when creating the Home Connect application. The log file should then show something like:
```
[HomeConnect] Home Connect request #19: POST https://api.home-connect.com/security/oauth/token
[HomeConnect] Home Connect request #19: OK +268ms
[HomeConnect] Refresh token 1234...1234567= (124 characters)
[HomeConnect] Access token  1234...3456789 (918 characters) (expires after 86400 seconds)
[HomeConnect] Refreshing access token in 82799 seconds
[HomeConnect] Scheduling configuration schema write
[HomeConnect] Starting events stream for all appliances
[HomeConnect] Home Connect request #20: STREAM https://api.home-connect.com/api/homeappliances/events
[HomeConnect] Home Connect request #21: GET https://api.home-connect.com/api/homeappliances
[HomeConnect] Home Connect authorisation token saved
[HomeConnect] Started events stream for all appliances
[HomeConnect] Home Connect request #21: OK +207ms
[HomeConnect] Found 3 appliances
```

If that sequence does not work for you then please:
1. Provide a copy of your full homebridge log file. Not just a few words from it.
2. Provide a much clearer explanation of what you are trying and the results.

**Comment by mistertropi** [comment]
Okay, thank you. There was a Problem with my Developer Account. I created a new one and it work. 

Thanks for the great Support of your plugin.

**Comment by thoukydides** [comment]
@mistertropi, good to hear that you managed to get it working.

If you figured out what was actually wrong, then it would be helpful if you could add a description here. It might assist anyone else who encounters similar issues...

**Comment by sanguino** [comment]
Same problem here, solved with different email addresses in my home connect and developer accounts
