### ISSUE TITLE
Notification possibility washingmachine event program finished

### ISSUE THREAD

**Issue by Thijsjuh92** [thoukydides/homebridge-homeconnect#63]
#### Description of Issue
How could i set a notifications when event is finished,

#### Home Connect Appliance(s)

Washing machine
#### HomeKit App(s)

Homeconnect
Apple home

#### Log File

```
```

**Comment by thoukydides** [comment]
If you mean iOS notifications then by far the easiest way is to use the official Home Connect app.

HomeKit only has limited support for generating notifications for specific state changes of a few accessory types, e.g. doors, windows, doorbells, and security sensors. None of the Services/Characteristics that generate those notifications are appropriate for Home Connect appliances so they are not supported by this plugin. Even if they were to be added, there would be no control over the text of the notification (other than the accessory name), so rather than saying that the program has finished it would report something like the curtains have opened.

What you can do with this plugin is to trigger a HomeKit automation when the program finishes. For Dryer / Washer / WasherDryer appliances the plugin creates two Programmable Switch Event buttons:
* Button 1 Single Press: Program Finished
* Button 2 Single Press: Program Aborted

You can use these to trigger an automation as a notification, e.g. switching on a light.

**Comment by thoukydides** [comment]
This was previously requested in issue #38.

**Comment by Thijsjuh92** [comment]
Thank you for your fast reply.
I,ll check the possibilities with running an other accessori as ghost switch with notification.
If i getting this working properly i revert how i did.

**Comment by Thijsjuh92** [comment]
After the last updates. I receive know a notification when the door is open and/or closed.
But still can't find a way to receive a notification from Home when a program is finished.. 

Anyone here already find a way to set this notification?

Door open and closed has an option  within the switch settings "Status and notifications"
Active Program only has "Status"..

Maybe within a future update possible to add to the active program a notification option, just like te door open/closed switch?

Thank you all in advance with idea's 👌🏽

**Comment by thoukydides** [comment]
> After the last updates. I receive know a notification when the door is open and/or closed.

The Home Connect API recently added support for opening the doors for some appliance types. To support that version 0.25.0 of this plugin added a `Door` service instead of adding the status as a non-standard characteristic on the main power `Switch`. This seemed like the cleanest approach rather than adding another generic `Switch` for this purpose.

By default Apple's Home app generates notifications for `Door` services changing state. This can be disabled on a per-device basis (and I quickly disabled it on my own devices since it doesn't serve any useful purpose).

> But still can't find a way to receive a notification from Home when a program is finished..

That's because Apple's Home app only generates notifications for a limited selection of services, e.g. doors, windows, blinds, doorbells, and a few sensor types. The `BSH.Common.Event.ProgramFinished` event triggers a `SINGLE` button press on a `StatelessProgrammableSwitch` service. Apple's Home app supports this as a trigger for an Automation, but does not have any support for using it to generate a notification.

This plugin cannot add extra notifications to the Home app. Only Apple can do that.

I will not be changing this plugin to use a different service type for these events since none of the other Apple-defined service types are suitable.

(By the way, please do not comments add to old closed issues - unless I spot the email notification I will never see the comment...)
