### ISSUE TITLE
Dishwasher timer

### ISSUE THREAD

**Issue by danlapid** [thoukydides/homebridge-homeconnect#68]
#### Description of Enhancement
Add a remaining time timer to the dishwasher accessory
I have another plug-in for he clothes washer that does this with the valve accessory 
The exact time remaining is being written to the logs all the time so the data is there

#### HomeKit Mapping
The valve service

#### Home Connect Appliance(s)
I have a Siemens dishwasher but I guess this is relevant to all dishwashers

**Comment by danlapid** [comment]
I added a pull request I did.
It's working for my appliance.
Would love your opinion.

**Comment by danlapid** [comment]
![1DE722BC-EAE0-4484-BF94-D1527F1770DF](https://user-images.githubusercontent.com/15655504/147992700-a0e40321-3f16-4df9-bfa8-9461f28c03de.png)

**Comment by thoukydides** [comment]
I prototyped this approach to using a Valve service early during this plugin's development. However, I decided against it because a Valve (regardless of whether configured to be of type Generic Valve, Irrigation, Shower Head, or Water Faucet) is not appropriate for most of the Home Connect appliance types that report a RemainingProgramTime.

At a stretch, a Valve is vaguely applicable to a Dishwasher or  a Washer/WasherDryer, and possibly a CoffeeMaker. However, it it is clearly unsuited to a Dryer, CookProcessor, Hood, or Oven.  This is why I ended up choosing to add the RemainingDuration characteristic to the Active Program Switch instead. This is visible in third-party HomeKit apps, and can be used to trigger automations. I still consider this to be the correct decision, as I have responded to previous requests along similar lines.

I have taken a quick look at the pull request provided, and whilst it may superficially work, there are some problems with the implementation. The main one is that it partially but incompletely replaces the Active Program Switch. It still creates that Switch, and some initialisation is performed for it, but subsequent updates to the status will be applied to the Valve instead which has not been properly initialised for that purpose. That could be fixed with some work, either by appropriately segregating functionality between the Switch and Valve, or by moving all of the Active Program functionality to the Valve for appliances that support RemainingProgramTime. The former would be much simpler to implement. The latter would be cleaner, but it would then be necessary to properly handle upgrades from earlier versions of this plugin by removing the legacy Switch service from HomeKit. Regardless of approach, this will also break any automations that use the characteristics that move to the Valve service.

Anyway, as explained above, I do not think this is a good change to make even if properly implemented. Hence, I am rejecting this request.
