### ISSUE TITLE
Pre-heating oven

### ISSUE THREAD

**Issue by Kroellie** [thoukydides/homebridge-homeconnect#70]
#### Description of Issue
I created a program for pre-heating my oven with the 'quick heat' option. However, the program runs by default for 1 minute. I explicitly do not set a duration, as I wouldn't do that on the device itself either. Setting a duration longer than 1 minute also seems 'wrong'. Shouldn't the absence of duration cause it to run indefinitely like it should?

#### Plugin Version
v0.23.3

**Comment by thoukydides** [comment]
Yes, that's how Home Connect programs work, unfortunately.

Each program that an appliance supports has a set of options. The options for a particular program always have a value - with the appliance providing its own default if none is specified via the API.

All Oven appliance programs include the [BSH.Common.Option.Duration](https://api-docs.home-connect.com/programs-and-options?#oven_duration-option) option. This requires a numeric duration in seconds. As you have discovered, if not specified this appears to default to 1 minute. The Home Connect API does not provide any way to start an Oven program without this option, or to specify a value of "infinity". The official Home Connect app has the same limitation - you cannot start an Oven program without also specifying a duration. The only way to start a program without a defined duration is on the appliance itself.

I similarly have a pre-heat program setup for my Oven. Due to this issue I specify a nominal duration of 3600 seconds (1 hour), which is sufficient for most of my usage, and if not I adjust the time on the oven when I put the food in.

**Comment by Kroellie** [comment]
Thanks for explaining and the awesome plugin!
