### ISSUE TITLE
Alarm timer, sabbath mode and special programs (steam, grill...)

### ISSUE THREAD

**Issue by ampmoor** [thoukydides/homebridge-homeconnect#77]
**Plugin Version:** 				homebridge-homeconnect v0.23.7
**Home Connect Appliance(s):** 	Siemens Oven (E-Nr: HN678G4S6/35)
**HomeKit App(s):**				Apple Home, Elgato Eve

First of all, thank you for the great work. I played around with it a bit and tested it with my Siemens oven. The following questions came up:

a) Is there a possibility to set the alarm timer?

_Ex.: BSH.Common.Setting.AlarmClock=3600_

b) The Sabbath Mode is always created with as a switch in HomeKit. Is it possible to prevent this?

c) Could additional oven programs be added?

Ex.:
_Cooking.Oven.Program.HeatingMode.GrillSmallArea
Cooking.Oven.Program.Dish.Automatic.Steam.BroetchenBaguette_

Error-Message:
[Backofen] Invalid program configuration ignored: Program key 'Cooking.Oven.Program.HeatingMode.GrillSmallArea' is not supported by the appliance
[Backofen] Invalid program configuration ignored: Program key 'Cooking.Oven.Program.Dish.Automatic.Steam.BroetchenBaguette' is not supported by the appliance

My config.json:

_{
    "platform": "HomeConnect",
    "clientid": „…“,
    "simulator": false,
    "language": {
        "api": "de-DE"
    },
    "SIEMENS-HN678G4S6-…“: {
        "programs": [
            {
                "name": "Hefeteig",
                "key": "Cooking.Oven.Program.HeatingMode.PreheatOvenware",
                "selectonly":false,
                "options":{
                    "Cooking.Oven.Option.SetpointTemperature":30,
                    "BSH.Common.Option.Duration":900,
                    "BSH.Common.Option.StartInRelative":0
                }
            },{
                "name": "Grill",
                "key": "Cooking.Oven.Program.HeatingMode.GrillSmallArea",
                "selectonly":false,
                "options":{
                    "BSH.Common.Option.Duration":900,
                    "BSH.Common.Option.StartInRelative":0
                }
            },{
                "name": "Vorheizen",
                "key": "Cooking.Oven.Program.HeatingMode.TopBottomHeating",
                "selectonly":false,
                "options":{
                    "Cooking.Oven.Option.SetpointTemperature":250,
                    "Cooking.Oven.Option.FastPreHeat":true,
                    "BSH.Common.Option.Duration": 3600,
                    "BSH.Common.Option.StartInRelative":0
                }
            },{
                "name":"Regenerieren",
                "key":"Cooking.Oven.Program.Dish.Automatic.Steam.BroetchenBaguette",
                "selectonly":false,
                "options":{
                    "BSH.Common.Option.Duration":1260
                }
            }
        ]
    }
}_

Even though the software already has a wide range of functions, an extension would make me very happy.

Greetings Olaf

**Comment by thoukydides** [comment]
> a) Is there a possibility to set the alarm timer?
>
> Ex.: BSH.Common.Setting.AlarmClock=3600

Only if Apple define new HomeKit services and characteristics that are appropriate for that functionality. None of the existing ones are obviously suitable, and I am not willing to bodge this onto services/characteristics with the wrong semantics since that causes problems when using Siri.

> b) The Sabbath Mode is always created with as a switch in HomeKit. Is it possible to prevent this?

I have no plans to add that sort of configuration option. There have been several previous requests along similar lines where I have explained my reasons in detail.

> c) Could additional oven programs be added?

This plugin reads the programs and the options they support from the Home Connect API. All programs and options exposed by the API are available for use. None of the programs or options are hardcoded or filtered by this plugin.

The only special case is for Hood appliances where Apple have defined less generic services and characteristics which provide a good mapping, so in that case the programs and options have special handling. This does not apply to Oven appliances though.

Hence, if the programs or options that you want to use are not supported then that would need to be resolved by the Home Connect team or the appliance manufacturer. You can contact them using this form: https://developer.home-connect.com/support/contact
