### ISSUE TITLE
Device "not reachable" in Home when remote start is send to unprepared device

### ISSUE THREAD

**Issue by solbadguy2010** [thoukydides/homebridge-homeconnect#79]
#### Description of Issue
I have my solar power inverter in Homekit. The currently generated power is shown as a Lux sensor. I created an automation to send my Siemens dishwasher and my Bosch washing mashine a "start" signal (If Lux value is above 2 switch on the "Active Program" switches of your plugin". This works perfectly if both machines are loaded and in "remote start" config. they start cleaning and use solar power to do so.

The problem starts when the devices get a start signal without beeing loaded. They then report "Device not reachable" in the Home app. Log looks fine. It reports, that "remote start" is not active.

Can you add some functionality to receive the start signal from home and report back "all good" to the app and then simply switch off the switch after some seconds if no "remote start" is possible?

#### Plugin Version
v0.23.7

#### Home Connect Appliance(s)
Bosch MAV28M40/01 and Siemens SX678X36TE/53

#### HomeKit App(s)
Apple Home

#### Diagnostic Checks
I started the prgramms manually and watched what is happening in the Home app.

#### Log File
[13/03/2022, 08:47:06] [HomeConnect] [Waschmaschine] START Program
[13/03/2022, 08:47:06] [HomeConnect] [Waschmaschine] Remote start not enabled on the appliance
[13/03/2022, 08:47:06] [HomeConnect] [Waschmaschine] START active program undefined
[13/03/2022, 08:48:05] [HomeConnect] [Geschirrspüler] START Program
[13/03/2022, 08:48:05] [HomeConnect] [Geschirrspüler] Remote start not enabled on the appliance
[13/03/2022, 08:48:05] [HomeConnect] [Geschirrspüler] START active program undefined

![IMG_6925](https://user-images.githubusercontent.com/30244171/158050750-ed2786c1-3f91-4198-81cc-efe8121d631c.PNG)

**Comment by solbadguy2010** [comment]
Additional Information: To get the device out of the error i need to re-start the devices or Homebridge. The "Active program" switch is greyed out after one try, so no auto-start is possible the next day.

**Comment by thoukydides** [comment]
Whilst I get the gist of what you have written, I might have misunderstood some of the details (terms like "start signal" and "loaded"  aren't really meaningful in a HomeKit/Homebridge context).

However, I think the crux of your request is that you do not want the plugin returning error status back to HomeKit when it is not possible to set a Characteristic to a requested state. If so, then I will NOT be making that change. That would prevent Siri from reporting when it has been unable to change the appliance state - something that I find extremely useful due to the Remote Start on my Oven being randomly switched off. Without that feedback I would think the Oven has switched on... only to find that my lunch isn't ready when I am ready to eat a few hours later...

**Comment by solbadguy2010** [comment]
OK, i see your usecase also. Maybe its possible to add some kind of "Solar Mode" so that i, as user, can control the behavior of the switch, so that is basically has two options:
1. When you switch on "Active Program" and remote start is not active report error to Homekit.
2. When you switch on "Active Program" and remote start is not active simply switch the switch back to "off".

Maybe there is even a mix of these two possible? When you switch on "Active Program" and remote start is not active report an error to Home Ap and after X Seconds revert switch back to off and the whole device back to normal. This way you would receive your error from Siri and i get my solar automation bahavior.

Or do you maybe know another way i can use? An API Call i can use with HTTP to do this, so i do not mess with your Plugin?

**Comment by solbadguy2010** [comment]
Oh, another idea. Would it be possible to see the status of "remote start" in Home? This way i could use an "IF" logic shortcut to ask first "is remote start active" and if yes i can switch on "Active Program".

**Comment by thoukydides** [comment]
> Or do you maybe know another way i can use? An API Call i can use with HTTP to do this, so i do not mess with your Plugin?

You could just use the Home Connect API directly. It is well documented and pretty straightforward. The only issue is that you would need to maintain an OAuth token.

> Would it be possible to see the status of "remote start" in Home? This way i could use an "IF" logic shortcut to ask first "is remote start active" and if yes i can switch on "Active Program".

This is already implemented using the `ProgramMode` Characteristic on the appliance’s main Power `Switch`. See https://github.com/thoukydides/homebridge-homeconnect/wiki/HomeKit-Mapping#extra-power-switch-characteristics

You will, however, need to use a third-party HomeKit app to see that though. The problem is that HomeKit doesn’t officially support accessories like these, so there aren’t any particularly appropriate Services or Characteristics for much of the functionality. Due to problems with Siri my strategy is to only use Apple-defined Services/Characteristics, to only use them with their intended semantics when they can be controlled, and to only add extra Characteristics when they don’t break Siri behaviour.

**Comment by solbadguy2010** [comment]
Ok. The problem is, that if i use an App like Eve i can see the additional characteristics but the Eve is not able to use „shortcuts“ and then there is no „if logic“. Would it not be possible to show „remote start“ as a window sensor in Home App? This also would not break siri i think. You would rather be apple to ask siri „is remote start closed?“. Something nice for your oven use case ;-)

**Comment by solbadguy2010** [comment]
Wait, this works. Was not aware eve has conditions :-)

![8076A22B-3022-419A-BD36-C8961AB0BF75](https://user-images.githubusercontent.com/30244171/158053777-0418a65d-7da1-494e-81e3-73da5945f48f.png)
