### ISSUE TITLE
Changelog available?

### ISSUE THREAD

**Issue by DJay-X** [thoukydides/homebridge-homeconnect#9]
Would be great to have a changelog available what is different or added in the versions.
Also great for people using config-ui-x because it is showing the changelog if provided before updating.

Thanks for the consideration.

**Comment by thoukydides** [comment]
I was planning on providing some form of changelog after the 1.0.0 release when the functionality will be more stable. Maintaining a worthwhile changelog at the moment would just slow development, and would either be full of small details that are irrelevant to most people or would be so vague as to be useless.

My current intention is to include this within the [README.md](https://github.com/thoukydides/homebridge-homeconnect/blob/master/README.md) since that is more obvious than a separate CHANGELOG.md to the (probably majority) of users who don't use [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x).

For now you will just have to look at the [commit history](https://github.com/thoukydides/homebridge-homeconnect/commits/master) and/or the descriptions that I add to the [open issues](https://github.com/thoukydides/homebridge-homeconnect/issues).

**Comment by thoukydides** [comment]
Added [CHANGELOG.md](https://github.com/thoukydides/homebridge-homeconnect/blob/master/CHANGELOG.md) in v0.13.0.
